// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Vehicle.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MMKiwi.CtaTracker.Model.Protobuf {

  /// <summary>Holder for reflection information generated from Vehicle.proto</summary>
  public static partial class VehicleReflection {

    #region Descriptor
    /// <summary>File descriptor for Vehicle.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VehicleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1WZWhpY2xlLnByb3RvGg9FcnJvckxpc3QucHJvdG8ihQMKB1ZlaGljbGUS",
            "CgoCaWQYASABKAkSFAoMbGFzdF91cGRhdGVkGAIgASgDEhAKCGxhdGl0dWRl",
            "GAMgASgBEhEKCWxvbmdpdHVkZRgEIAEoARIPCgdoZWFkaW5nGAUgASgBEg8K",
            "B3BhdHRlcm4YBiABKAUSFAoMcGF0dGVybl9kaXN0GAcgASgBEg0KBXJvdXRl",
            "GAggASgJEhMKC2Rlc3RpbmF0aW9uGAkgASgJEhIKCmlzX2RlbGF5ZWQYCiAB",
            "KAgSDQoFc3BlZWQYCyABKAUSEgoKdGFfdHJpcF9pZBgMIAEoCRITCgt0YV9i",
            "bG9ja19pZBgNIAEoCRIbChNvcmlnaW5hbF90YV90cmlwX2lkGA4gASgJEgwK",
            "BHpvbmUYDyABKAkSDAoEbW9kZRgQIAEoBRIWCg5wYXNzZW5nZXJfbG9hZBgR",
            "IAEoCRIcChRzY2hlZHVsZWRfc3RhcnRfdGltZRgSIAEoBRIcChRzY2hlZHVs",
            "ZWRfc3RhcnRfZGF0ZRgTIAEoCSJWCg9WZWhpY2xlUmVzcG9uc2USGgoGcmVz",
            "dWx0GAEgASgLMgguVmVoaWNsZUgAEhsKBWVycm9yGAIgASgLMgouRXJyb3JM",
            "aXN0SABCCgoIcmVzcG9uc2VCJUgDqgIgTU1LaXdpLkN0YVRyYWNrZXIuTW9k",
            "ZWwuUHJvdG9idWZQAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MMKiwi.CtaTracker.Model.Protobuf.ErrorListReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MMKiwi.CtaTracker.Model.Protobuf.Vehicle), global::MMKiwi.CtaTracker.Model.Protobuf.Vehicle.Parser, new[]{ "Id", "LastUpdated", "Latitude", "Longitude", "Heading", "Pattern", "PatternDist", "Route", "Destination", "IsDelayed", "Speed", "TaTripId", "TaBlockId", "OriginalTaTripId", "Zone", "Mode", "PassengerLoad", "ScheduledStartTime", "ScheduledStartDate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MMKiwi.CtaTracker.Model.Protobuf.VehicleResponse), global::MMKiwi.CtaTracker.Model.Protobuf.VehicleResponse.Parser, new[]{ "Result", "Error" }, new[]{ "Response" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Vehicle : pb::IMessage<Vehicle>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Vehicle> _parser = new pb::MessageParser<Vehicle>(() => new Vehicle());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Vehicle> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MMKiwi.CtaTracker.Model.Protobuf.VehicleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Vehicle() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Vehicle(Vehicle other) : this() {
      id_ = other.id_;
      lastUpdated_ = other.lastUpdated_;
      latitude_ = other.latitude_;
      longitude_ = other.longitude_;
      heading_ = other.heading_;
      pattern_ = other.pattern_;
      patternDist_ = other.patternDist_;
      route_ = other.route_;
      destination_ = other.destination_;
      isDelayed_ = other.isDelayed_;
      speed_ = other.speed_;
      taTripId_ = other.taTripId_;
      taBlockId_ = other.taBlockId_;
      originalTaTripId_ = other.originalTaTripId_;
      zone_ = other.zone_;
      mode_ = other.mode_;
      passengerLoad_ = other.passengerLoad_;
      scheduledStartTime_ = other.scheduledStartTime_;
      scheduledStartDate_ = other.scheduledStartDate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Vehicle Clone() {
      return new Vehicle(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "last_updated" field.</summary>
    public const int LastUpdatedFieldNumber = 2;
    private long lastUpdated_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LastUpdated {
      get { return lastUpdated_; }
      set {
        lastUpdated_ = value;
      }
    }

    /// <summary>Field number for the "latitude" field.</summary>
    public const int LatitudeFieldNumber = 3;
    private double latitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Latitude {
      get { return latitude_; }
      set {
        latitude_ = value;
      }
    }

    /// <summary>Field number for the "longitude" field.</summary>
    public const int LongitudeFieldNumber = 4;
    private double longitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Longitude {
      get { return longitude_; }
      set {
        longitude_ = value;
      }
    }

    /// <summary>Field number for the "heading" field.</summary>
    public const int HeadingFieldNumber = 5;
    private double heading_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Heading {
      get { return heading_; }
      set {
        heading_ = value;
      }
    }

    /// <summary>Field number for the "pattern" field.</summary>
    public const int PatternFieldNumber = 6;
    private int pattern_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Pattern {
      get { return pattern_; }
      set {
        pattern_ = value;
      }
    }

    /// <summary>Field number for the "pattern_dist" field.</summary>
    public const int PatternDistFieldNumber = 7;
    private double patternDist_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double PatternDist {
      get { return patternDist_; }
      set {
        patternDist_ = value;
      }
    }

    /// <summary>Field number for the "route" field.</summary>
    public const int RouteFieldNumber = 8;
    private string route_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Route {
      get { return route_; }
      set {
        route_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "destination" field.</summary>
    public const int DestinationFieldNumber = 9;
    private string destination_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Destination {
      get { return destination_; }
      set {
        destination_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "is_delayed" field.</summary>
    public const int IsDelayedFieldNumber = 10;
    private bool isDelayed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsDelayed {
      get { return isDelayed_; }
      set {
        isDelayed_ = value;
      }
    }

    /// <summary>Field number for the "speed" field.</summary>
    public const int SpeedFieldNumber = 11;
    private int speed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Speed {
      get { return speed_; }
      set {
        speed_ = value;
      }
    }

    /// <summary>Field number for the "ta_trip_id" field.</summary>
    public const int TaTripIdFieldNumber = 12;
    private string taTripId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaTripId {
      get { return taTripId_; }
      set {
        taTripId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ta_block_id" field.</summary>
    public const int TaBlockIdFieldNumber = 13;
    private string taBlockId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaBlockId {
      get { return taBlockId_; }
      set {
        taBlockId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "original_ta_trip_id" field.</summary>
    public const int OriginalTaTripIdFieldNumber = 14;
    private string originalTaTripId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OriginalTaTripId {
      get { return originalTaTripId_; }
      set {
        originalTaTripId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "zone" field.</summary>
    public const int ZoneFieldNumber = 15;
    private string zone_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Zone {
      get { return zone_; }
      set {
        zone_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mode" field.</summary>
    public const int ModeFieldNumber = 16;
    private int mode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Mode {
      get { return mode_; }
      set {
        mode_ = value;
      }
    }

    /// <summary>Field number for the "passenger_load" field.</summary>
    public const int PassengerLoadFieldNumber = 17;
    private string passengerLoad_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PassengerLoad {
      get { return passengerLoad_; }
      set {
        passengerLoad_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "scheduled_start_time" field.</summary>
    public const int ScheduledStartTimeFieldNumber = 18;
    private int scheduledStartTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ScheduledStartTime {
      get { return scheduledStartTime_; }
      set {
        scheduledStartTime_ = value;
      }
    }

    /// <summary>Field number for the "scheduled_start_date" field.</summary>
    public const int ScheduledStartDateFieldNumber = 19;
    private string scheduledStartDate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ScheduledStartDate {
      get { return scheduledStartDate_; }
      set {
        scheduledStartDate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Vehicle);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Vehicle other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (LastUpdated != other.LastUpdated) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Latitude, other.Latitude)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Longitude, other.Longitude)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Heading, other.Heading)) return false;
      if (Pattern != other.Pattern) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(PatternDist, other.PatternDist)) return false;
      if (Route != other.Route) return false;
      if (Destination != other.Destination) return false;
      if (IsDelayed != other.IsDelayed) return false;
      if (Speed != other.Speed) return false;
      if (TaTripId != other.TaTripId) return false;
      if (TaBlockId != other.TaBlockId) return false;
      if (OriginalTaTripId != other.OriginalTaTripId) return false;
      if (Zone != other.Zone) return false;
      if (Mode != other.Mode) return false;
      if (PassengerLoad != other.PassengerLoad) return false;
      if (ScheduledStartTime != other.ScheduledStartTime) return false;
      if (ScheduledStartDate != other.ScheduledStartDate) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (LastUpdated != 0L) hash ^= LastUpdated.GetHashCode();
      if (Latitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Latitude);
      if (Longitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Longitude);
      if (Heading != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Heading);
      if (Pattern != 0) hash ^= Pattern.GetHashCode();
      if (PatternDist != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(PatternDist);
      if (Route.Length != 0) hash ^= Route.GetHashCode();
      if (Destination.Length != 0) hash ^= Destination.GetHashCode();
      if (IsDelayed != false) hash ^= IsDelayed.GetHashCode();
      if (Speed != 0) hash ^= Speed.GetHashCode();
      if (TaTripId.Length != 0) hash ^= TaTripId.GetHashCode();
      if (TaBlockId.Length != 0) hash ^= TaBlockId.GetHashCode();
      if (OriginalTaTripId.Length != 0) hash ^= OriginalTaTripId.GetHashCode();
      if (Zone.Length != 0) hash ^= Zone.GetHashCode();
      if (Mode != 0) hash ^= Mode.GetHashCode();
      if (PassengerLoad.Length != 0) hash ^= PassengerLoad.GetHashCode();
      if (ScheduledStartTime != 0) hash ^= ScheduledStartTime.GetHashCode();
      if (ScheduledStartDate.Length != 0) hash ^= ScheduledStartDate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (LastUpdated != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(LastUpdated);
      }
      if (Latitude != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Latitude);
      }
      if (Longitude != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Longitude);
      }
      if (Heading != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Heading);
      }
      if (Pattern != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Pattern);
      }
      if (PatternDist != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(PatternDist);
      }
      if (Route.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Route);
      }
      if (Destination.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Destination);
      }
      if (IsDelayed != false) {
        output.WriteRawTag(80);
        output.WriteBool(IsDelayed);
      }
      if (Speed != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Speed);
      }
      if (TaTripId.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(TaTripId);
      }
      if (TaBlockId.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(TaBlockId);
      }
      if (OriginalTaTripId.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(OriginalTaTripId);
      }
      if (Zone.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(Zone);
      }
      if (Mode != 0) {
        output.WriteRawTag(128, 1);
        output.WriteInt32(Mode);
      }
      if (PassengerLoad.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(PassengerLoad);
      }
      if (ScheduledStartTime != 0) {
        output.WriteRawTag(144, 1);
        output.WriteInt32(ScheduledStartTime);
      }
      if (ScheduledStartDate.Length != 0) {
        output.WriteRawTag(154, 1);
        output.WriteString(ScheduledStartDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (LastUpdated != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(LastUpdated);
      }
      if (Latitude != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Latitude);
      }
      if (Longitude != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Longitude);
      }
      if (Heading != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Heading);
      }
      if (Pattern != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Pattern);
      }
      if (PatternDist != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(PatternDist);
      }
      if (Route.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Route);
      }
      if (Destination.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Destination);
      }
      if (IsDelayed != false) {
        output.WriteRawTag(80);
        output.WriteBool(IsDelayed);
      }
      if (Speed != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Speed);
      }
      if (TaTripId.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(TaTripId);
      }
      if (TaBlockId.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(TaBlockId);
      }
      if (OriginalTaTripId.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(OriginalTaTripId);
      }
      if (Zone.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(Zone);
      }
      if (Mode != 0) {
        output.WriteRawTag(128, 1);
        output.WriteInt32(Mode);
      }
      if (PassengerLoad.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(PassengerLoad);
      }
      if (ScheduledStartTime != 0) {
        output.WriteRawTag(144, 1);
        output.WriteInt32(ScheduledStartTime);
      }
      if (ScheduledStartDate.Length != 0) {
        output.WriteRawTag(154, 1);
        output.WriteString(ScheduledStartDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (LastUpdated != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LastUpdated);
      }
      if (Latitude != 0D) {
        size += 1 + 8;
      }
      if (Longitude != 0D) {
        size += 1 + 8;
      }
      if (Heading != 0D) {
        size += 1 + 8;
      }
      if (Pattern != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Pattern);
      }
      if (PatternDist != 0D) {
        size += 1 + 8;
      }
      if (Route.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Route);
      }
      if (Destination.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Destination);
      }
      if (IsDelayed != false) {
        size += 1 + 1;
      }
      if (Speed != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Speed);
      }
      if (TaTripId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaTripId);
      }
      if (TaBlockId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaBlockId);
      }
      if (OriginalTaTripId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OriginalTaTripId);
      }
      if (Zone.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Zone);
      }
      if (Mode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Mode);
      }
      if (PassengerLoad.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(PassengerLoad);
      }
      if (ScheduledStartTime != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(ScheduledStartTime);
      }
      if (ScheduledStartDate.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ScheduledStartDate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Vehicle other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.LastUpdated != 0L) {
        LastUpdated = other.LastUpdated;
      }
      if (other.Latitude != 0D) {
        Latitude = other.Latitude;
      }
      if (other.Longitude != 0D) {
        Longitude = other.Longitude;
      }
      if (other.Heading != 0D) {
        Heading = other.Heading;
      }
      if (other.Pattern != 0) {
        Pattern = other.Pattern;
      }
      if (other.PatternDist != 0D) {
        PatternDist = other.PatternDist;
      }
      if (other.Route.Length != 0) {
        Route = other.Route;
      }
      if (other.Destination.Length != 0) {
        Destination = other.Destination;
      }
      if (other.IsDelayed != false) {
        IsDelayed = other.IsDelayed;
      }
      if (other.Speed != 0) {
        Speed = other.Speed;
      }
      if (other.TaTripId.Length != 0) {
        TaTripId = other.TaTripId;
      }
      if (other.TaBlockId.Length != 0) {
        TaBlockId = other.TaBlockId;
      }
      if (other.OriginalTaTripId.Length != 0) {
        OriginalTaTripId = other.OriginalTaTripId;
      }
      if (other.Zone.Length != 0) {
        Zone = other.Zone;
      }
      if (other.Mode != 0) {
        Mode = other.Mode;
      }
      if (other.PassengerLoad.Length != 0) {
        PassengerLoad = other.PassengerLoad;
      }
      if (other.ScheduledStartTime != 0) {
        ScheduledStartTime = other.ScheduledStartTime;
      }
      if (other.ScheduledStartDate.Length != 0) {
        ScheduledStartDate = other.ScheduledStartDate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            LastUpdated = input.ReadInt64();
            break;
          }
          case 25: {
            Latitude = input.ReadDouble();
            break;
          }
          case 33: {
            Longitude = input.ReadDouble();
            break;
          }
          case 41: {
            Heading = input.ReadDouble();
            break;
          }
          case 48: {
            Pattern = input.ReadInt32();
            break;
          }
          case 57: {
            PatternDist = input.ReadDouble();
            break;
          }
          case 66: {
            Route = input.ReadString();
            break;
          }
          case 74: {
            Destination = input.ReadString();
            break;
          }
          case 80: {
            IsDelayed = input.ReadBool();
            break;
          }
          case 88: {
            Speed = input.ReadInt32();
            break;
          }
          case 98: {
            TaTripId = input.ReadString();
            break;
          }
          case 106: {
            TaBlockId = input.ReadString();
            break;
          }
          case 114: {
            OriginalTaTripId = input.ReadString();
            break;
          }
          case 122: {
            Zone = input.ReadString();
            break;
          }
          case 128: {
            Mode = input.ReadInt32();
            break;
          }
          case 138: {
            PassengerLoad = input.ReadString();
            break;
          }
          case 144: {
            ScheduledStartTime = input.ReadInt32();
            break;
          }
          case 154: {
            ScheduledStartDate = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            LastUpdated = input.ReadInt64();
            break;
          }
          case 25: {
            Latitude = input.ReadDouble();
            break;
          }
          case 33: {
            Longitude = input.ReadDouble();
            break;
          }
          case 41: {
            Heading = input.ReadDouble();
            break;
          }
          case 48: {
            Pattern = input.ReadInt32();
            break;
          }
          case 57: {
            PatternDist = input.ReadDouble();
            break;
          }
          case 66: {
            Route = input.ReadString();
            break;
          }
          case 74: {
            Destination = input.ReadString();
            break;
          }
          case 80: {
            IsDelayed = input.ReadBool();
            break;
          }
          case 88: {
            Speed = input.ReadInt32();
            break;
          }
          case 98: {
            TaTripId = input.ReadString();
            break;
          }
          case 106: {
            TaBlockId = input.ReadString();
            break;
          }
          case 114: {
            OriginalTaTripId = input.ReadString();
            break;
          }
          case 122: {
            Zone = input.ReadString();
            break;
          }
          case 128: {
            Mode = input.ReadInt32();
            break;
          }
          case 138: {
            PassengerLoad = input.ReadString();
            break;
          }
          case 144: {
            ScheduledStartTime = input.ReadInt32();
            break;
          }
          case 154: {
            ScheduledStartDate = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class VehicleResponse : pb::IMessage<VehicleResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VehicleResponse> _parser = new pb::MessageParser<VehicleResponse>(() => new VehicleResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VehicleResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MMKiwi.CtaTracker.Model.Protobuf.VehicleReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VehicleResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VehicleResponse(VehicleResponse other) : this() {
      switch (other.ResponseCase) {
        case ResponseOneofCase.Result:
          Result = other.Result.Clone();
          break;
        case ResponseOneofCase.Error:
          Error = other.Error.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VehicleResponse Clone() {
      return new VehicleResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MMKiwi.CtaTracker.Model.Protobuf.Vehicle Result {
      get { return responseCase_ == ResponseOneofCase.Result ? (global::MMKiwi.CtaTracker.Model.Protobuf.Vehicle) response_ : null; }
      set {
        response_ = value;
        responseCase_ = value == null ? ResponseOneofCase.None : ResponseOneofCase.Result;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MMKiwi.CtaTracker.Model.Protobuf.ErrorList Error {
      get { return responseCase_ == ResponseOneofCase.Error ? (global::MMKiwi.CtaTracker.Model.Protobuf.ErrorList) response_ : null; }
      set {
        response_ = value;
        responseCase_ = value == null ? ResponseOneofCase.None : ResponseOneofCase.Error;
      }
    }

    private object response_;
    /// <summary>Enum of possible cases for the "response" oneof.</summary>
    public enum ResponseOneofCase {
      None = 0,
      Result = 1,
      Error = 2,
    }
    private ResponseOneofCase responseCase_ = ResponseOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseOneofCase ResponseCase {
      get { return responseCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResponse() {
      responseCase_ = ResponseOneofCase.None;
      response_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VehicleResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VehicleResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Result, other.Result)) return false;
      if (!object.Equals(Error, other.Error)) return false;
      if (ResponseCase != other.ResponseCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (responseCase_ == ResponseOneofCase.Result) hash ^= Result.GetHashCode();
      if (responseCase_ == ResponseOneofCase.Error) hash ^= Error.GetHashCode();
      hash ^= (int) responseCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (responseCase_ == ResponseOneofCase.Result) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      if (responseCase_ == ResponseOneofCase.Error) {
        output.WriteRawTag(18);
        output.WriteMessage(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (responseCase_ == ResponseOneofCase.Result) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      if (responseCase_ == ResponseOneofCase.Error) {
        output.WriteRawTag(18);
        output.WriteMessage(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (responseCase_ == ResponseOneofCase.Result) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      if (responseCase_ == ResponseOneofCase.Error) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VehicleResponse other) {
      if (other == null) {
        return;
      }
      switch (other.ResponseCase) {
        case ResponseOneofCase.Result:
          if (Result == null) {
            Result = new global::MMKiwi.CtaTracker.Model.Protobuf.Vehicle();
          }
          Result.MergeFrom(other.Result);
          break;
        case ResponseOneofCase.Error:
          if (Error == null) {
            Error = new global::MMKiwi.CtaTracker.Model.Protobuf.ErrorList();
          }
          Error.MergeFrom(other.Error);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::MMKiwi.CtaTracker.Model.Protobuf.Vehicle subBuilder = new global::MMKiwi.CtaTracker.Model.Protobuf.Vehicle();
            if (responseCase_ == ResponseOneofCase.Result) {
              subBuilder.MergeFrom(Result);
            }
            input.ReadMessage(subBuilder);
            Result = subBuilder;
            break;
          }
          case 18: {
            global::MMKiwi.CtaTracker.Model.Protobuf.ErrorList subBuilder = new global::MMKiwi.CtaTracker.Model.Protobuf.ErrorList();
            if (responseCase_ == ResponseOneofCase.Error) {
              subBuilder.MergeFrom(Error);
            }
            input.ReadMessage(subBuilder);
            Error = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::MMKiwi.CtaTracker.Model.Protobuf.Vehicle subBuilder = new global::MMKiwi.CtaTracker.Model.Protobuf.Vehicle();
            if (responseCase_ == ResponseOneofCase.Result) {
              subBuilder.MergeFrom(Result);
            }
            input.ReadMessage(subBuilder);
            Result = subBuilder;
            break;
          }
          case 18: {
            global::MMKiwi.CtaTracker.Model.Protobuf.ErrorList subBuilder = new global::MMKiwi.CtaTracker.Model.Protobuf.ErrorList();
            if (responseCase_ == ResponseOneofCase.Error) {
              subBuilder.MergeFrom(Error);
            }
            input.ReadMessage(subBuilder);
            Error = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
